version: '3'

services:
  db:
    image: mongo
    restart: always
    platform: linux/x86_64
    networks:
      - localnetwork
    ports:
      - "27018:27017"
    container_name: mongodb

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - localnetwork
    container_name: buffview-service

networks:
  localnetwork:
